//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAuthenticationDbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAnswer()
        {
            this.UserAnswerSequences = new HashSet<UserAnswerSequence>();
        }
    
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> QuestionKeyId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual QuestionKey QuestionKey { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnswerSequence> UserAnswerSequences { get; set; }
    }
}
