//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAuthenticationDbFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswerSequence
    {
        public int Id { get; set; }
        public Nullable<int> QuestionKeyId { get; set; }
        public int SequenceNumber { get; set; }
        public int UserAnswerId { get; set; }
    
        public virtual QuestionKey QuestionKey { get; set; }
        public virtual UserAnswer UserAnswer { get; set; }
    }
}
